### ISSUE TITLE
Introduction: Adefolake Durosinmi

### ISSUE THREAD

**Issue by blaackpanther85** [Mboalab/Outreachy_May_2023-August_2023-Internships#153]
My name is Adefolake Durosinmi, I am a Cybersecurity professional. I am looking forward to learning and working on this project. This is the first engagement on github

Social Media Handle

LinkedIn: https://www.linkedin.com/in/adefolake-durosinmi-a7a22664

And my portfolio can be found in the link below. Which include my career path and interest.

http://6413cfcfe3555.site123.me/

**Comment by PetraAG** [comment]
Close this issue and record a contribution.
